return {
  "folke/which-key.nvim",
  enabled = true,
  event = "VeryLazy",
  opts = {
    spec = {
      { "d", hidden = true },
      { "dd", hidden = true },
      { "D", hidden = true },
      { "DD", hidden = true },
      { "s", hidden = true },
      { "S", hidden = true },
      { "SH", hidden = true },
      { "SV", hidden = true },
      { "gc", hidden = true },
      { "gcc", hidden = true },
      { "g=", hidden = true },
      { "g==", hidden = true },
      { "gx", hidden = true },
      { "gxx", hidden = true },
      { "gm", hidden = true },
      { "gmm", hidden = true },
      { "gs", hidden = true },
      { "gss", hidden = true },
      { "gr", hidden = true },
      { "grr", hidden = true },
      { "<leader>c", hidden = true },
      { "<leader>q", hidden = true },
      { "<leader>f", hidden = true },
      { "sh", hidden = true },
      { "sd", hidden = true },
      { "sr", hidden = true },
      { "sf", hidden = true },
      { "sF", hidden = true },
      { "sa", hidden = true },
      { "i", mode = { "x", "o" }, hidden = true },
      { "a", mode = { "x", "o" }, hidden = true },
      { "s", mode = { "x", "s" }, hidden = true },
      { "sq", mode = { "x", "s" }, hidden = true },
    },
  },
  keys = {
    {
      "<leader>?",
      function()
        require("which-key").show({ global = false })
      end,
      desc = "Buffer Local Keymaps (which-key)",
    },
  },
}
